apiVersion: v1
kind: Service
metadata:
  name: dynaone-svc
  namespace: dynaone
spec:
  selector:
    app: dynaone
  type: ClusterIP
  ports:
    - name: dynaone-svc-http-port
      port: 8080
      targetPort: 8080

